name: Lightweight Test Airflow DAGs

on:
  push:
    branches:
      - main
    paths:
      - "Airflow/dags/**"

jobs:
  validate-dags:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install Airflow and DAG Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow
          if [ -f Airflow/requirements.txt ]; then
            pip install -r Airflow/requirements.txt
          fi

      # Step 4: Validate DAG Syntax
      - name: Validate DAG Syntax
        run: |
          for dag in Airflow/dags/*.py; do
            echo "Validating $dag"
            python "$dag"
          done

      # Step 5: Lint DAG Files
      - name: Lint DAG Files
        run: |
          pip install flake8
          flake8 Airflow/dags/