name: Lightweight Test Airflow DAGs

on:
  push:
    branches:
      - main
    paths:
      - "Airflow/dags/**"

jobs:
  validate-dags:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow pytest

      # Step 4: Validate DAG Syntax
      - name: Validate DAG Syntax
        run: |
          for dag in Airflow/dags/*.py; do
            python "$dag"
          done

      # Step 5: Run Unit Tests (if applicable)
      - name: Run Unit Tests
        run: |
          pytest tests/
